name: pharmacy_arrival
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.1+2

environment:
  sdk: ">=2.19.0"
  flutter: ">=3.7.0"


dependencies:
  another_flushbar: ^1.12.29
  bot_toast: ^4.0.3
  cached_network_image: ^3.2.3
  code_field: ^1.22.0
  cupertino_icons: ^1.0.5
  dartz: ^0.10.1
  device_info: ^2.0.3
  device_info_plus: ^8.1.0
  dio: ^4.0.6
  dotted_line: ^3.1.0
  dropdown_search: ^5.0.6
  equatable: ^2.0.5
  file_picker: ^5.2.6
  flutter:
    sdk: flutter
  flutter_barcode_scanner: ^2.0.0
  flutter_bloc: ^8.1.2
  flutter_localizations:
    sdk: flutter
  flutter_masked_text: ^0.8.0
  flutter_multi_formatter: ^2.10.2
  flutter_secure_storage: ^8.0.0
  flutter_svg: ^2.0.4 
  fluttertoast: ^8.0.9
  freezed_annotation: ^2.0.3
  get_it: ^7.2.0
  google_fonts: ^4.0.3
  hive: ^2.2.1
  hive_flutter: ^1.1.0
  image_gallery_saver: ^1.7.1
  image_picker: ^0.8.7
  internet_connection_checker: ^1.0.0+1
  intl: ^0.17.0
  json_annotation: ^4.5.0
  json_serializable: ^6.1.6
  loader_overlay: ^2.0.4
  logger: ^1.1.0
  lottie: ^2.3.0
  mask_text_input_formatter: ^2.1.0
  mobile_scanner: ^1.1.2
  permission_handler: ^10.2.0
  pin_code_fields: ^7.3.0
  provider: ^6.0.0
  pull_to_refresh: ^2.0.0
  qr_flutter: ^4.0.0
  scrollable_positioned_list: ^0.3.5
  search_choices: ^2.0.20
  shared_preferences: ^2.0.11
  signature: ^5.0.0
  syncfusion_flutter_calendar: ^20.4.54
  syncfusion_flutter_datepicker: ^20.4.54
  syncfusion_localizations: ^20.4.54
  table_calendar: ^3.0.3
  uri_to_file: ^0.2.0
  url_launcher: ^6.1.2

dev_dependencies:
  build_runner: ^2.3.3
  flutter_launcher_icons: ^0.12.0
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  lint: ^2.0.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/png/app_icon.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/png/app_icon_foreground.png"

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/svg/
    - assets/images/png/
    - assets/lotties/

flutter_intl:
  enabled: true
  fonts:
    - family: SFProDisplay
      fonts:
        - asset: fonts/SFProDisplay-Regular.ttf
        - asset: fonts/SFProDisplay-RegularItalic.ttf
          style: italic
        - asset: fonts/SFProDisplay-Thin.ttf
          weight: 100
        - asset: fonts/SFProDisplay-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: fonts/SFProDisplay-Light.ttf
          weight: 300
        - asset: fonts/SFProDisplay-LightItalic.ttf
          weight: 300
          style: italic
        - asset: fonts/SFProDisplay-Medium.ttf
          weight: 500
        - asset: fonts/SFProDisplay-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: fonts/SFProDisplay-Semibold.ttf
          weight: 600
        - asset: fonts/SFProDisplay-SemiboldItalic.ttf
          weight: 600
          style: italic
        - asset: fonts/SFProDisplay-Bold.ttf
          weight: 700
        - asset: fonts/SFProDisplay-BlackItalic.ttf
          weight: 700
          style: italic
        - asset: fonts/SFProDisplay-Black.ttf
          weight: 900
        - asset: fonts/SFProDisplay-BlackItalic.ttf
          weight: 900
          style: italic
    - family: DelaGothicOne
      fonts:
        - asset: fonts/DelaGothicOne-Regular.ttf
    - family: SFProDisplay
      fonts:
        - asset: fonts/ProductSans-Regular.ttf
        - asset: fonts/ProductSans-Italic.ttf
          style: italic
        - asset: fonts/ProductSans-Thin.ttf
          weight: 100
        - asset: fonts/ProductSans-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: fonts/ProductSans-Light.ttf
          weight: 300
        - asset: fonts/ProductSans-LightItalic.ttf
          weight: 300
          style: italic
        - asset: fonts/ProductSans-Medium.ttf
          weight: 500
        - asset: fonts/ProductSans-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: fonts/ProductSans-Bold.ttf
          weight: 700
        - asset: fonts/ProductSans-BlackItalic.ttf
          weight: 700
          style: italic
        - asset: fonts/ProductSans-Black.ttf
          weight: 900
        - asset: fonts/ProductSans-BlackItalic.ttf
          weight: 900
          style: italic