name: pharmacy_arrival
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  # another_xlider: ^1.0.1+2
  another_flushbar: ^1.10.24
  bot_toast: ^4.0.2
  cached_network_image: ^3.1.0
  # camera: ^0.9.4+16
  code_field: ^1.22.0
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  device_info: ^2.0.3
  device_info_plus: ^3.2.2
  dio: ^4.0.3
  dotted_line: ^3.0.0
  dropdown_search: ^5.0.2
  equatable: ^2.0.3
  file_picker: ^4.5.1
  firebase_analytics: ^8.3.2
  firebase_core: ^1.6.0
  firebase_crashlytics: ^2.2.1
  firebase_dynamic_links: ^3.0.1
  firebase_messaging: ^11.1.0
  flutter:
    sdk: flutter
  flutter_barcode_scanner: ^2.0.0
  flutter_bloc: ^8.0.0
  flutter_local_notifications: ^9.3.2
  flutter_localizations:
    sdk: flutter
  flutter_masked_text: 0.8.0
  flutter_multi_formatter: ^2.4.1
  flutter_secure_storage: ^5.0.2
  flutter_svg: ^0.23.0+1
  fluttertoast: ^8.0.9
  freezed_annotation: ^2.0.3
  get_it: ^7.2.0
  google_fonts: ^2.3.1
  hive: ^2.2.1
  hive_flutter: ^1.1.0
  image_gallery_saver: ^1.7.1
  image_picker: ^0.8.4+4
  internet_connection_checker: ^0.0.1+3
  intl: ^0.17.0
  json_annotation: ^4.5.0
  json_serializable: ^6.1.6
  loader_overlay: ^2.0.4
  logger: ^1.1.0
  lottie: ^1.2.2
  mask_text_input_formatter: ^2.1.0
  mobile_scanner: ^1.1.1
  permission_handler: ^9.2.0
  pin_code_fields: ^7.3.0
  provider: ^6.0.0
  pull_to_refresh: ^2.0.0
  qr_flutter: ^4.0.0
  # qr_code_scanner: 
  #   git:
  #     url: https://github.com/X-SLAYER/qr_code_scanner.git
  #     ref: flutter-beta
  shared_preferences: ^2.0.11
  scrollable_positioned_list: ^0.3.5
  search_choices: ^2.0.20
  signature: ^5.0.0
  syncfusion_flutter_calendar: ^19.4.54
  syncfusion_flutter_datepicker: ^19.4.54
  syncfusion_localizations: ^19.4.48
  table_calendar: ^3.0.3
  uri_to_file: ^0.2.0
  url_launcher: ^6.1.2

dev_dependencies:
  build_runner: ^2.1.10
  flutter_launcher_icons: ^0.10.0
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.1.1
  lint: ^1.8.2

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/png/app_icon.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/png/app_icon_foreground.png"

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/svg/
    - assets/images/png/
    - assets/lotties/

flutter_intl:
  enabled: true
  fonts:
    - family: SFProDisplay
      fonts:
        - asset: fonts/SFProDisplay-Regular.ttf
        - asset: fonts/SFProDisplay-RegularItalic.ttf
          style: italic
        - asset: fonts/SFProDisplay-Thin.ttf
          weight: 100
        - asset: fonts/SFProDisplay-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: fonts/SFProDisplay-Light.ttf
          weight: 300
        - asset: fonts/SFProDisplay-LightItalic.ttf
          weight: 300
          style: italic
        - asset: fonts/SFProDisplay-Medium.ttf
          weight: 500
        - asset: fonts/SFProDisplay-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: fonts/SFProDisplay-Semibold.ttf
          weight: 600
        - asset: fonts/SFProDisplay-SemiboldItalic.ttf
          weight: 600
          style: italic
        - asset: fonts/SFProDisplay-Bold.ttf
          weight: 700
        - asset: fonts/SFProDisplay-BlackItalic.ttf
          weight: 700
          style: italic
        - asset: fonts/SFProDisplay-Black.ttf
          weight: 900
        - asset: fonts/SFProDisplay-BlackItalic.ttf
          weight: 900
          style: italic
    - family: DelaGothicOne
      fonts:
        - asset: fonts/DelaGothicOne-Regular.ttf
    - family: SFProDisplay
      fonts:
        - asset: fonts/ProductSans-Regular.ttf
        - asset: fonts/ProductSans-Italic.ttf
          style: italic
        - asset: fonts/ProductSans-Thin.ttf
          weight: 100
        - asset: fonts/ProductSans-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: fonts/ProductSans-Light.ttf
          weight: 300
        - asset: fonts/ProductSans-LightItalic.ttf
          weight: 300
          style: italic
        - asset: fonts/ProductSans-Medium.ttf
          weight: 500
        - asset: fonts/ProductSans-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: fonts/ProductSans-Bold.ttf
          weight: 700
        - asset: fonts/ProductSans-BlackItalic.ttf
          weight: 700
          style: italic
        - asset: fonts/ProductSans-Black.ttf
          weight: 900
        - asset: fonts/ProductSans-BlackItalic.ttf
          weight: 900
          style: italic